projet_Gestion_Rh/Controllers/CongeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using projet_Gestion_Rh.Models;

namespace projet_Gestion_Rh.Controllers
{
    [Authorize]

    public class CongeController : Controller
    {
        private readonly RhDBContext _dbContext;
        private readonly IWebHostEnvironment webHostEnvironment;




        public CongeController(RhDBContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._dbContext = dbContext;
            this.webHostEnvironment = webHostEnvironment;
        }
        // GET: CongeController
        public ActionResult Index()
        {

            List<Conge> conges = _dbContext.Conges.Include(x => x.Employe).ToList();
            foreach (var congé in conges)
            {
                TimeSpan duree = congé.DateFin - congé.DateDebut;
                congé.Duree = duree.TotalDays; 
            }

            return View(conges);
        }

        // GET: CongeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CongeController/Create
        public ActionResult Create()
        {
            ViewBag.EmployesList = _dbContext.Employes.ToList();

            return View();
        }

        // POST: CongeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Conge conge)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (_dbContext.Conges.Where(x => x.CongeId == conge.CongeId).Count() > 0)
                    {
                        ViewBag.errormessage = "le  conges est existe deja pour un employe";
                        return View(conge);
                    }
                    Conge c = new Conge();
                    c.Type = conge.Type;
                    _dbContext.Conges.Add(conge);
                    _dbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                return View(conge);

            }
            catch
            {
                return View(conge);
            }

        }

        // GET: CongeController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.EmployesList = _dbContext.Employes.ToList();
            Conge con = _dbContext.Conges.Find(id);
            return View(con);
        }

        // POST: CongeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Conge conge)
        {
            try
            {
                Conge con = _dbContext.Conges.Find(id);
                con.Type = conge.Type;
                con.DateDebut = conge.DateDebut;
                con.DateFin = conge.DateFin;
                con.Status = conge.Status;
                con.EmployeId = conge.EmployeId;



                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            
            Conge conge = _dbContext.Conges
                .Include(c => c.Employe) 
                .FirstOrDefault(c => c.CongeId == id);

            if (conge == null)
            {
                return NotFound();
            }

            return View(conge);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Conge conge)
        {
            try
            {
                _dbContext.Conges.Remove(conge);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

projet_Gestion_Rh/Controllers/DepartementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using projet_Gestion_Rh.Models;

namespace projet_Gestion_Rh.Controllers
{
    [Authorize]

    public class DepartementController : Controller
    {

        private readonly RhDBContext _dbContext;
        private readonly IWebHostEnvironment webHostEnvironment;




        public DepartementController(RhDBContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._dbContext = dbContext;
            this.webHostEnvironment = webHostEnvironment;
        }
        // GET: DepartementController
        public ActionResult Index()
        {
            List<Departement> departements = _dbContext.Departements.ToList();
            return View(departements);
        }

        // GET: DepartementController
        public ActionResult GetEmploye(int id)
        {
            List<Employe> ListEmpl = new List<Employe>(); 
            foreach(Employe e in _dbContext.Employes.ToList())
            {
                if(e.DepartementId == id)
                {
                   
                    ListEmpl.Add(e);
                    
                }
            }
            return View(ListEmpl);
        }


        // GET: DepartementController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DepartementController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepartementController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Departement departement)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (_dbContext.Departements.Where(x => x.Nom == departement.Nom).Count() > 0)
                    {
                        ViewBag.errormessage = "le departement existe";
                        return View(departement);
                    }
                    Departement s = new Departement();
                    s.Nom = departement.Nom;
                    _dbContext.Departements.Add(departement);
                    _dbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                return View(departement);

            }
            catch
            {
                return View(departement);
            }
        }





        // GET: DepartementController/Edit/5
        public ActionResult Edit(int id)
        {
            Departement depart = _dbContext.Departements.Find(id);
            return View(depart);
        }

        // POST: DepartementController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Departement departement)
        {

            try
            {
                Departement depart = _dbContext.Departements.Find(id);
                depart.Nom = departement.Nom;
                depart.Description = departement.Description;
                depart.NomResponsable = departement.NomResponsable;



                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartementController/Delete/5
        public ActionResult Delete(int id)
        {
            Departement depart = _dbContext.Departements.Find(id);
            return View(depart);
        }

        // POST: DepartementController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Departement departement)
        {
            try
            {
                _dbContext.Departements.Remove(departement);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

projet_Gestion_Rh/Controllers/EmployeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.Internal;
using NuGet.Protocol;
using projet_Gestion_Rh.Models;
using System;
using System.Drawing.Drawing2D;
using System.Web;
using static NuGet.Packaging.PackagingConstants;

namespace projet_Gestion_Rh.Controllers
{

    [Authorize]
    public class EmployeController : Controller
    {

        private readonly RhDBContext _dbContext;
        private readonly IWebHostEnvironment webHostEnvironment;




        public EmployeController(RhDBContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._dbContext = dbContext;
            this.webHostEnvironment = webHostEnvironment;
        }
        // GET: EmployeController
        public ActionResult Index(string search)
        {
            IQueryable<Employe> query = _dbContext.Employes.Include(x => x.Departement).Include(y=>y.Poste);

            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(e => e.NomPrenom.Contains(search));
            }

            List<Employe> employes = query.ToList();
            return View(employes);
        }


        // GET: EmployeController/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }

            Employe employee = _dbContext.Employes
                .Include(e => e.Departement)
                .Include(e => e.Poste)
                .FirstOrDefault(e => e.EmployeId == id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }


        // GET: EmployeController/Create
        public ActionResult Create(Departement departement)
        {
            ViewBag.DepartementsList = _dbContext.Departements.ToList();
            ViewBag.PostesList = _dbContext.Postes.ToList();

            return View();
        }

        // POST: EmployeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employe employe)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    if (_dbContext.Employes.Where(x => x.NomPrenom == employe.NomPrenom).Count() > 0)
                    {
                        ViewBag.errormessage = "L'employee existe deja !";
                        return View(employe);
                    }

                    string folder = "image/cover/";
                    folder += Guid.NewGuid().ToString() + "_" + employe.imageFile.FileName;
                    string serverFolder = Path.Combine(webHostEnvironment.WebRootPath, folder);
                    //folder
                    employe.Image = folder;
                    employe.imageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    _dbContext.Employes.Add(employe);
                    _dbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));


                }
                return View(employe);


            }
            catch
            {
                return View(employe);
            }
        }


        // GET: EmployeController/Edit/5
        public IActionResult Edit(int id)
        {
            ViewBag.DepartementsList = _dbContext.Departements.ToList();
            ViewBag.PostesList = _dbContext.Postes.ToList();

            Employe emp = _dbContext.Employes.Find(id);
            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Employe e)
        {
            try
            {
                Employe emp = _dbContext.Employes.Find(id);
                if (e.imageFile != null)
                {
                    if (!string.IsNullOrEmpty(emp.Image))
                    {
                        string filepath = Path.Combine(webHostEnvironment.WebRootPath, "image/cover", emp.Image);
                        if (System.IO.File.Exists(filepath))
                        {
                            System.IO.File.Delete(filepath);
                        }
                    }

                    string folder = "image/cover/";
                    folder += Guid.NewGuid().ToString() + "_" + e.imageFile.FileName;
                    string serverFolder = Path.Combine(webHostEnvironment.WebRootPath, folder);

                    // Update the e.Image property
                    e.Image = folder;

                    e.imageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }

                emp.NomPrenom = e.NomPrenom;
                emp.DateNaissance = e.DateNaissance;
                emp.Genre = e.Genre;
                emp.Telephone = e.Telephone;
                emp.Adresse = e.Adresse;
                emp.Email = e.Email;
                emp.DateEmbauche = e.DateEmbauche;
                emp.Image = e.Image;
                emp.DepartementId = e.DepartementId;
                emp.PosteId = e.PosteId;


                _dbContext.Employes.Update(emp);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }






        // GET: EmployeController/Delete/5
        public ActionResult Delete(int id)
        {
            Employe employe = _dbContext.Employes
      .Include(e => e.Departement)
      .Include(e => e.Poste)
      .FirstOrDefault(e => e.EmployeId == id);
            Employe emplo = _dbContext.Employes.Find(id);
            return View(emplo);
        }

        // POST: EmployeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Employe employe)
        {
            try
            {
                _dbContext.Employes.Remove(employe);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

projet_Gestion_Rh/Controllers/PosteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using projet_Gestion_Rh.Models;

namespace projet_Gestion_Rh.Controllers
{
    [Authorize]

    public class PosteController : Controller
    {


        private readonly RhDBContext _dbContext;
        private readonly IWebHostEnvironment webHostEnvironment;


        public PosteController(RhDBContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._dbContext = dbContext;
            this.webHostEnvironment = webHostEnvironment;
        }
        // GET: PosteController
        public ActionResult Index()
        {
            List<Poste> Postes = _dbContext.Postes.ToList();
            return View(Postes);
        }

        // GET: PosteController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PosteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PosteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Poste poste)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (_dbContext.Postes.Where(x => x.Titre == poste.Titre).Count() > 0)
                    {
                        ViewBag.errormessage = "le poste existe";
                        return View(poste);
                    }
                    Poste p = new Poste();
                    p.Titre = poste.Titre;
                    p.Description = poste.Description;
                    p.salaire = poste.salaire;
                    _dbContext.Postes.Add(poste);
                    _dbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                return View(poste);

            }
            catch
            {
                return View(poste);
            }

        }

        // GET: PosteController/Edit/5
        public ActionResult Edit(int id)
        {
            Poste poste = _dbContext.Postes.Find(id);
            return View(poste);
        }

        // POST: PosteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Poste poste)
        {
            try
            {
                Poste p = _dbContext.Postes.Find(id);
                p.Titre = poste.Titre;
                p.Description = poste.Description;
                p.salaire = poste.salaire;



                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PosteController/Delete/5
        public ActionResult Delete(int id)
        {
            Poste poste = _dbContext.Postes.Find(id);
            return View(poste);
        }

        // POST: PosteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Poste poste)
        {
            try
            {
                _dbContext.Postes.Remove(poste);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

projet_Gestion_Rh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>@ViewData["Title"] - projet_Gestion_Rh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projet_Gestion_Rh.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.17.0/font/bootstrap-icons.css">
    <style>
        body {
            background-color: #f0f0f0; /* Light gray background color */
        }

        .navbar {
            background-color: #343a40; /* Dark background color for the navbar */
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1); /* Subtle shadow effect */
        }

        .navbar-brand {
            font-size: 24px;
        }

        .navbar-toggler {
            border: none; /* Remove border from the toggle button */
        }

        .navbar-toggler-icon {
            font-size: 24px; /* Set the font size for the toggle button icon */
            color: #fff; /* White color for the toggle button icon */
        }

        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #001a33; /* Bleu foncé pour la sidebar */
            color: #818181;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidebar a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 18px;
                color: #818181;
                display: block;
                transition: 0.3s;
            }

                .sidebar a:hover {
                    color: #f1f1f1;
                }

            .sidebar .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        #main {
            transition: margin-left .5s;
            padding: 16px;
        }

        .container {
            margin-top: 20px; /* Add margin space at the top */
        }

        .footer {
            background-color: #343a40; /* Dark background color for the footer */
            color: #fff; /* White text color for the footer */
            padding: 10px 0;
        }

        .icon-margin {
            margin-right: 8px; /* ou la valeur de marge que vous préférez */
        }

        .custom-bg-darkblue {
            background-color: #001f3f; /* Remplacez cette valeur par la couleur bleu foncé que vous préférez */
            color: #fff; /* Couleur du texte en blanc pour contraster */
            /* Ajoutez d'autres styles si nécessaire */
        }

        .text-white {
            color: #fff; /* Couleur blanche */
        }

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-***" crossorigin="anonymous" / >
    </style>
</head>
<body>
    <header>
        <div id="mySidebar" class="sidebar">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="fas fa-home"></i>
                Home
            </a>


            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                <i class="fas fa-info-circle"></i>
                About
            </a>
            <a class="nav-link" asp-area="" asp-controller="Employe" asp-action="Index">
                <i class="fas fa-user"></i>
                List Employees
            </a>
            <a class="nav-link" asp-area="" asp-controller="Departement" asp-action="Index">
                <i class="fas fa-building"></i>
                Départements
            </a>

              <a class="nav-link" asp-area="" asp-controller="Poste" asp-action="Index">
                <i class="fas fa-briefcase"></i>
                Poste

            </a>

   <a class="nav-link" asp-area="" asp-controller="Conge" asp-action="Index">
                <i class="far fa-calendar-alt"></i>
                Conge
            </a>
        </div>

        <div id="main">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm custom-bg-darkblue border-right box-shadow mb-3">
                <div class="container-fluid">

                    <span style="font-size:30px;cursor:pointer; color: #fff;" onclick="openNav()">☰</span>&nbsp;&nbsp;&nbsp;

                    <a class="navbar-brand navbar-dark text-white font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house-door"></i> Gestion RH
                    </a>



                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <!-- Add your links here if needed -->
                        </ul>

                        <!-- Add the search form inside the navbar -->
                        <form class="d-flex" method="get" action="@Url.Action("Index", "Employe")">
                            <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-light" type="submit">
                                <i class="bi bi-search"></i> Search
                            </button>
                        </form>
                    </div>
                </div>
                <div class="text-white">
            <partial name="_LoginPartial"/>

            </div>
            </nav>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="text-center text-white custom-bg-darkblue">
    <div class="container p-4 pb-0">
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <button data-mdb-ripple-init type="button" class="btn btn-outline-light btn-rounded">
              RhWeAreTeam.com 
          </button>
        </p>
      </section>
    </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">

      <a class="text-white" href="https://mdbootstrap.com/"> Entreprise We Are Team</a>
    </div>

    </div>
    <!-- Copyright -->
  </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>